nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/Tym17

feed: 
projects_url: http://github.com/Tym17

customize:
    gravatar:
        email:
    logo:
        enabled: false
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/Tym17/KosmoKot
    show_all_posts: false
    post_count: 5
    highlight: rainbow

plugins:
    # Github Issues -> comments
    github_comments: Tym17/KosmoKot # Github repo for mirroring Issues to comments
    github_admins:
    - Tym17 # add your Github name or more if you want admin highlight on comments

    disqus_shortname: # Disqus Comments Shortname
    google_analytics: #UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
